# Generated by Django 5.2.3 on 2025-06-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_actions'),
        ('products', '0007_product_updated_at'),
    ]

    operations = [
    ]
